name: Generate Fake Activity

on:
  schedule:
    - cron: "*/1 * * * *" # svaka minuta
  workflow_dispatch: # ručno pokretanje

jobs:
  call-fake-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST "https://utjttkibkkfwyepsfyie.supabase.co/functions/v1/generate-fake-activity" \
            -H "Authorization: Bearer ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0anR0a2lia2tmd3llcHNmeWllIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDY4NDAyMCwiZXhwIjoyMDU2MjYwMDIwfQ.IPtrPwII03Va2K8XRs43e_X_CjMmMCUjAg5laE3T1wU }}" \
            -H "Content-Type: application/json" \
            -d '{}'
